### ISSUE TITLE
please review feature/fasterMysql

### ISSUE THREAD

**Issue by MuschPusch** [stmh/drupal-docker#3]
Check this commit: https://github.com/stmh/drupal-docker/commit/784f7e610ea5a125904631075bd8b67c2dc17678

See the mysqladmin docs for --silent and ping. http://dev.mysql.com/doc/refman/5.6/en/mysqladmin.html

Somewhere in the docs: 

_If you execute mysqladmin shutdown when connecting to a local server using a Unix socket file, mysqladmin waits until the server's process ID file has been removed, to ensure that the server has stopped properly._

So that's why i think we don't need to wait after the mysqladmin shutdown.

This reduces the docker startup time to a couple of seconds.

**Comment by stmh** [comment]
Nice findings. Works on my end. Please merge to develop if you want.
